# Generated by Django 4.0.9 on 2026-04-04 08:11

import device.models.device
import device.models.ota
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(help_text='Desc of the user', max_length=500)),
                ('subnet_mask', models.CharField(help_text='Subnet mask', max_length=20)),
                ('dev_image', models.ImageField(blank=True, help_text='Avatar of the device', null=True, upload_to=device.models.device.get_image_path)),
                ('device_data_token', models.CharField(blank=True, max_length=40, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DevCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_name', models.CharField(help_text='Name of command.', max_length=255)),
                ('command_code', models.CharField(help_text='Command code.', max_length=20)),
            ],
            options={
                'verbose_name': 'Device Command',
                'verbose_name_plural': 'Device Commands',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the device', max_length=20, null=True, unique=True)),
                ('mac', models.CharField(blank=True, help_text='Device MAC', max_length=255, null=True)),
                ('alias', models.CharField(blank=True, help_text='Device alias', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Display name of the device', max_length=255, null=True)),
                ('installation_date', models.DateField(blank=True, help_text="Device's installation date", null=True)),
                ('device_contact_number', models.CharField(blank=True, help_text='Contact number of the device.', max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Avatar of the device', null=True, upload_to=device.models.device.get_image_path)),
                ('position', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=40, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('commands', models.ManyToManyField(blank=True, to='device.devcommand')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the equipment', max_length=255)),
                ('max_power', models.IntegerField(help_text='Max power consumption of the equipment')),
                ('min_power', models.IntegerField(help_text='Min power consumption of the equipment')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the branch', max_length=100)),
                ('address', models.CharField(help_text='Address of the branch', max_length=500)),
                ('pin_code', models.IntegerField(help_text='PIN code')),
                ('contact_number', models.CharField(help_text='Contact number', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Avatar of the operator', null=True, upload_to=device.models.device.get_image_path)),
            ],
            options={
                'verbose_name': 'Device Operator',
                'verbose_name_plural': 'Device Operator',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subnet_a', models.IntegerField(help_text='subnet_a')),
                ('subnet_b', models.IntegerField(help_text='subnet_b')),
                ('subnet_c', models.IntegerField(help_text='subnet_c')),
                ('subnet_d', models.IntegerField(help_text='subnet_d')),
            ],
            options={
                'verbose_name': 'Subnet',
                'verbose_name_plural': 'Subnets',
            },
        ),
        migrations.CreateModel(
            name='UserDeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name', max_length=255)),
                ('code', models.CharField(help_text='Type code', max_length=255)),
                ('identifier_field', models.CharField(help_text='Field in the data schema to identify the device to which the data belongs to', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('data_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device Type',
                'verbose_name_plural': 'User Device Types',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name', max_length=255)),
                ('target_type', models.CharField(choices=[('meter', 'meter'), ('user', 'user'), ('alarm', 'alarm'), ('device', 'device'), ('report', 'report')], help_text='Resulting status type', max_length=255)),
                ('update_trigger', models.CharField(choices=[('data', 'Data'), ('schedule', 'Schedule'), ('data/schedule', 'Data and Schedule')], help_text='Status update trigger', max_length=255)),
                ('last_trigger_time', models.DateTimeField(blank=True, null=True)),
                ('translation_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.userdevicetype')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Type',
                'verbose_name_plural': 'Status Types',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data_arrival_time', models.DateTimeField(db_index=True)),
                ('data', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
            ],
            options={
                'verbose_name': 'RawData',
                'verbose_name_plural': 'RawData',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('meter_type', models.CharField(choices=[('AC_METER', 'AC_METER'), ('DC_METER', 'DC_METER'), ('HOUSEHOLD_AC_METER', 'HOUSEHOLD_AC_METER'), ('LOAD_AC_METER', 'LOAD_AC_METER'), ('LOAD_DC_METER', 'LOAD_DC_METER'), ('INVERTER_AC_METER', 'INVERTER_AC_METER'), ('INVERTER_DC_METER', 'INVERTER_DC_METER'), ('WEATHER_METER', 'WEATHER_METER'), ('IMPORT_ENERGY_METER', 'IMPORT_ENERGY_METER'), ('EXPORT_ENERGY_METER', 'EXPORT_ENERGY_METER')], help_text='Meter type', max_length=1024)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(blank=True, help_text='Document type', max_length=255, null=True)),
                ('doc_name', models.CharField(blank=True, help_text='Document name', max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=device.models.device.get_image_path)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_created_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Document',
                'verbose_name_plural': 'Device Documents',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Devices Status',
            },
        ),
        migrations.CreateModel(
            name='DeviceProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('val_type', models.CharField(choices=[('I', 'Int'), ('F', 'Float'), ('S', 'String')], default='S', max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Property',
                'verbose_name_plural': 'Device Properties',
            },
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to=device.models.ota.get_firmware_path)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.devicetype')),
            ],
            options={
                'verbose_name': 'Device Firmware',
                'verbose_name_plural': 'Device Firmware',
            },
        ),
        migrations.CreateModel(
            name='DeviceEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('quantity', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.equipment')),
            ],
            options={
                'verbose_name': 'Device Equipment',
                'verbose_name_plural': 'Device Equipments',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'verbose_name': 'Device Config',
                'verbose_name_plural': 'Device Config',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.userdevicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Operator of the device', null=True, on_delete=django.db.models.deletion.CASCADE, to='device.operator'),
        ),
        migrations.AddField(
            model_name='device',
            name='types',
            field=models.ManyToManyField(blank=True, to='device.devicetype'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(help_text="Command's status(E:Executed or P:Pending)", max_length=1)),
                ('command_in_time', models.DateTimeField(help_text='Command arrival time')),
                ('command_read_time', models.DateTimeField(blank=True, help_text='Time when the command was read by the remote device', null=True)),
                ('command', models.CharField(help_text='Command', max_length=20)),
                ('param', models.CharField(help_text='Command parameter', max_length=100)),
                ('response', models.TextField(blank=True, help_text='Command response', null=True)),
                ('response_time', models.DateTimeField(blank=True, help_text='Time when response was received', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(to='device.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['-data_arrival_time'], name='device_rawd_data_ar_2bc434_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['device', '-data_arrival_time'], name='device_rawd_device__14828d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['channel', '-data_arrival_time'], name='device_rawd_channel_a15975_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['data_type', '-data_arrival_time'], name='device_rawd_data_ty_9f816d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['device', 'channel', '-data_arrival_time'], name='device_rawd_device__46e6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['-created_at'], name='device_devi_created_cbc444_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['name', '-created_at'], name='device_devi_name_660373_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['device', '-created_at'], name='device_devi_device__968384_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['user', '-created_at'], name='device_devi_user_id_ae8fb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('ip_address',)},
        ),
    ]
