# Generated by Django 2.2 on 2021-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210317_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(choices=[('Home', 'Home'), ('Charge Controller', 'Charge Controller'), ('DELTA-RPI Inverter', 'DELTA-RPI Inverter'), ('WEATHER_STATION', 'WEATHER STATION'), ('OTHER', 'OTHER')], help_text='Type name', max_length=50),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('AC_METER', 'AC_METER'), ('DC_METER', 'DC_METER'), ('LOAD_AC_METER', 'LOAD_AC_METER'), ('HOUSEHOLD_AC_METER', 'HOUSEHOLD_AC_METER'), ('INVETER_AC_METER', 'INVETER_AC_METER'), ('INVETER_DC_METER', 'INVETER_DC_METER'), ('WEATHER_METER', 'WEATHER_METER')], max_length=50),
        ),
    ]
