# Generated by Django 2.2 on 2021-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210911_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceequipment',
            name='meter_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
