# Generated by Django 2.2 on 2021-10-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceequipment_meter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='device',
        ),
        migrations.RemoveField(
            model_name='meterdata',
            name='meter',
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='device',
        ),
        migrations.DeleteModel(
            name='DerivedData',
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
        migrations.DeleteModel(
            name='MeterData',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
