# Generated by Django 4.0.9 on 2026-09-09 12:29

import device.models.device
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '__first__'),
        ('event', '0004_alter_action_device_command_alter_eventtype_operator'),
        ('device', '0004_add_status_report_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(blank=True, help_text='Document type', max_length=255, null=True)),
                ('doc_name', models.CharField(blank=True, help_text='Document name', max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=device.models.device.get_image_path)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset/Device Document',
                'verbose_name_plural': 'Asset/Device Documents',
                'db_table': 'device_document',
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asset.asset')),
            ],
            options={
                'verbose_name': 'Asset/Device Status',
                'verbose_name_plural': 'Asset/Device Statuses',
                'db_table': 'device_devicestatus',
            },
        ),
        migrations.CreateModel(
            name='StatusCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Cache',
                'verbose_name_plural': 'Status Caches',
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='devicestatus',
                    name='device',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='devicestatus',
                    name='user',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='device',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='device',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='device',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='device',
            name='types',
        ),
        migrations.AlterField(
            model_name='devicefirmware',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.userdevicetype'),
        ),
        migrations.DeleteModel(
            name='DevCommand',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='DeviceStatus',
                ),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.AddField(
            model_name='statuscache',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device'),
        ),
        migrations.AddField(
            model_name='statuscache',
            name='status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.statustype'),
        ),
        migrations.AddField(
            model_name='statuscache',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='assetstatus',
                    name='device',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='assetstatus',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='statuscache',
            index=models.Index(fields=['device', '-updated_at'], name='device_stat_device__6b91c9_idx'),
        ),
        migrations.AddIndex(
            model_name='statuscache',
            index=models.Index(fields=['user', '-updated_at'], name='device_stat_user_id_e2559a_idx'),
        ),
        migrations.AddIndex(
            model_name='statuscache',
            index=models.Index(fields=['status_type', '-updated_at'], name='device_stat_status__6cedba_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatus',
            index=models.Index(fields=['-created_at'], name='device_devi_created_cbc444_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatus',
            index=models.Index(fields=['name', '-created_at'], name='device_devi_name_660373_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatus',
            index=models.Index(fields=['device', '-created_at'], name='device_devi_device__968384_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatus',
            index=models.Index(fields=['asset', '-created_at'], name='device_devi_asset_i_10655b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatus',
            index=models.Index(fields=['user', '-created_at'], name='device_devi_user_id_ae8fb7_idx'),
        ),
    ]
