# Generated by Django 4.0.9 on 2026-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_assetdocument_assetstatus_statuscache_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statuscache',
            name='device_stat_status__6cedba_idx',
        ),
        migrations.RemoveField(
            model_name='statuscache',
            name='status_type',
        ),
        migrations.AddField(
            model_name='userdevicetype',
            name='device_type',
            field=models.CharField(choices=[('IOT_GATEWAY_GENERIC', 'IOT_GATEWAY_GENERIC'), ('IOT_GATEWAY_ENERGY', 'IOT_GATEWAY_ENERGY')], default='IOT_GATEWAY_GENERIC', help_text='Device type', max_length=255),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('AC_METER', 'AC_METER'), ('DC_METER', 'DC_METER'), ('HOUSEHOLD_AC_METER', 'HOUSEHOLD_AC_METER'), ('LOAD_AC_METER', 'LOAD_AC_METER'), ('LOAD_DC_METER', 'LOAD_DC_METER'), ('INVERTER_AC_METER', 'INVERTER_AC_METER'), ('INVERTER_DC_METER', 'INVERTER_DC_METER'), ('WEATHER_METER', 'WEATHER_METER'), ('IMPORT_ENERGY_METER', 'IMPORT_ENERGY_METER'), ('EXPORT_ENERGY_METER', 'EXPORT_ENERGY_METER'), ('NET_ENERGY_METER', 'NET_ENERGY_METER')], help_text='Meter type', max_length=1024),
        ),
    ]
