# Generated by Django 4.0.9 on 2026-10-06 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_remove_statuscache_device_stat_status__6cedba_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('data_point', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('power', models.DecimalField(decimal_places=3, max_digits=8)),
                ('data_arrival_time', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
            ],
            options={
                'verbose_name': 'MeterLoad',
                'verbose_name_plural': 'MeterLoads',
            },
        ),
        migrations.AddIndex(
            model_name='meterload',
            index=models.Index(fields=['device', '-data_arrival_time'], name='device_mete_device__f38e87_idx'),
        ),
        migrations.AddIndex(
            model_name='meterload',
            index=models.Index(fields=['equipment_name', '-data_arrival_time'], name='device_mete_equipme_5bdec7_idx'),
        ),
    ]
