# Generated by Django 2.2.16 on 2021-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_devicestatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='name',
            field=models.CharField(blank=True, choices=[('DAILY_STATUS', 'DAILY_STATUS'), ('LAST_WEEK_REPORT', 'LAST_WEEK_REPORT'), ('LAST_MONTH_REPORT', 'LAST_MONTH_REPORT')], max_length=255, null=True),
        ),
    ]
