# Generated by Django 2.2.16 on 2021-12-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20211210_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AlterModelOptions(
            name='devcommand',
            options={'verbose_name': 'Device Command', 'verbose_name_plural': 'Device Commands'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'verbose_name': 'Device Status', 'verbose_name_plural': 'Devices Status'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Device Document', 'verbose_name_plural': 'Device Documents'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Device Operator', 'verbose_name_plural': 'Device Operator'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
