# Generated by Django 2.2.16 on 2022-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20211211_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(choices=[('Home', 'Home'), ('Charge Controller', 'Charge Controller'), ('DELTA-RPI Inverter', 'DELTA-RPI Inverter'), ('WEATHER_STATION', 'WEATHER STATION'), ('SOLAR HYBRID INVERTER', 'SOLAR HYBRID INVERTER'), ('IOT_GATEWAY', 'IOT_GATEWAY'), ('OTHER', 'OTHER')], help_text='Type name', max_length=50),
        ),
    ]
