# Generated by Django 4.0.9 on 2026-04-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(blank=True, help_text='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")', max_length=200, null=True, verbose_name='Task Name')),
                ('args', models.JSONField(blank=True, help_text='JSON encoded positional arguments (Example: ["arg1", "arg2"])', null=True, verbose_name='Positional Arguments')),
                ('kwargs', models.JSONField(blank=True, help_text='JSON encoded keyword arguments (Example: {"argument": "value"})', null=True, verbose_name='Keyword Arguments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('device_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.devcommand')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equation_threshold', models.CharField(blank=True, help_text='Threshold value for the event equations', max_length=255, null=True)),
                ('last_trigger_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device.device')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
            ],
            options={
                'verbose_name_plural': 'Device events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Event type name', max_length=255)),
                ('description', models.TextField(help_text='Description')),
                ('trigger_type', models.CharField(choices=[('Data', 'Data triggered event.'), ('Time', 'Time triggered event.')], max_length=20)),
                ('equation', models.TextField(blank=True, help_text='Trigger equation', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.action')),
                ('device_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.deviceevent')),
            ],
            options={
                'verbose_name_plural': 'Events history',
            },
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='device_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.deviceevent'),
        ),
    ]
