# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('notification', '__first__'),
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('command_param', models.CharField(blank=True, max_length=255, null=True)),
                ('device_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.DevCommand')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_threshold', models.CharField(blank=True, help_text='Threshold value for the event equations', max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device.Device')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('device_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.DeviceEvent')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event type name', max_length=255)),
                ('description', models.TextField(help_text='Description')),
                ('trigger_type', models.CharField(choices=[('Data', 'Data triggered event.'), ('Time', 'Time triggered event.')], max_length=20)),
                ('equation', models.TextField(blank=True, help_text='Trigger equation', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device.User'),
        ),
        migrations.AddField(
            model_name='action',
            name='device_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.DeviceEvent'),
        ),
        migrations.AddField(
            model_name='action',
            name='notifications',
            field=models.ManyToManyField(to='notification.Notification'),
        ),
    ]
