# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_deviceevent_scheduled_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceevent',
            name='schedule',
        ),
    ]
