# Generated by Django 2.2.16 on 2021-12-07 15:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('notification', '0002_sentnotification'),
        ('event', '0003_remove_deviceevent_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventHistory',
        ),
        migrations.RemoveField(
            model_name='action',
            name='command_param',
        ),
        migrations.RemoveField(
            model_name='action',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='deviceevent',
            name='scheduled_task',
        ),
        migrations.AddField(
            model_name='action',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON encoded positional arguments (Example: ["arg1", "arg2"])', null=True, verbose_name='Positional Arguments'),
        ),
        migrations.AddField(
            model_name='action',
            name='kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON encoded keyword arguments (Example: {"argument": "value"})', null=True, verbose_name='Keyword Arguments'),
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.CharField(blank=True, help_text='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")', max_length=200, null=True, verbose_name='Task Name'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule'),
        ),
    ]
