# Generated by Django 4.0.9 on 2026-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtype_deviceevent_alarm_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='device_command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='operator',
            field=models.CharField(blank=True, choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equals'), ('lt', 'Less Than'), ('lte', 'Less Than or Equals'), ('contains', 'Contains')], max_length=16, null=True),
        ),
    ]
