# Generated by Django 2.2.16 on 2021-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20211210_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='last_trigger_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
