# Generated by Django 2.2.16 on 2021-12-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_deviceevent_last_trigger_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='deviceevent',
            options={'verbose_name_plural': 'Device events'},
        ),
        migrations.AlterModelOptions(
            name='eventhistory',
            options={'verbose_name_plural': 'Events history'},
        ),
    ]
