# IOT_GW_DEVICES
IOT_GATEWAY = "IOT_GATEWAY"
IOT_GW_V1 = "IOT-GW-V1"
IOT_GW_V1_CC_WIFI = "IOT-GW-V1-CC-WIFI"
IOT_GW_V1_MODBUS_WIFI = "IOT-GW-V1-MODBUS-WIFI"
IOT_GW_V1_MODBUS_GSM = "IOT-GW-V1-MODBUS-GSM"
IOT_GW_V2_MODBUS_WIFI = 'IOT-GW-V2-MODBUS-WIFI'

# STATCON INVERTER GATEWAY
IOT_GW_STATCON = "IOT-GW-STATCON"
IOT_GW_SHAKTI_SOLAR_PUMP = "IOT-GW-SHAKTI-SOLAR-PUMP"

IOT_GW_DEVICES = [
    IOT_GATEWAY,
    IOT_GW_V1,
    IOT_GW_V1_CC_WIFI,
    IOT_GW_V1_MODBUS_WIFI,
    IOT_GW_V1_MODBUS_GSM,
    IOT_GW_V2_MODBUS_WIFI,
    IOT_GW_SHAKTI_SOLAR_PUMP
]

OTHER_GATEWAYS = [
    IOT_GW_STATCON,
    IOT_GW_SHAKTI_SOLAR_PUMP
]
