# Generated by Django 4.0.9 on 2026-04-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('S', 'Via SMS'), ('E', 'Via email'), ('P', 'Push notification'), ('HG', 'HTTP GET request'), ('HP', 'HTTP POST request'), ('TB', 'Telegram bot')], max_length=2)),
                ('sent', models.BooleanField(default=False)),
                ('mobiles', models.TextField(blank=True, help_text='Comma separated list of mobile numbers.', null=True)),
                ('emails', models.TextField(blank=True, help_text='Comma separated list of emails.', null=True)),
                ('urls', models.TextField(blank=True, help_text='Comma separated list of URLs.', null=True)),
                ('title', models.CharField(blank=True, help_text='Notification title', max_length=255, null=True)),
                ('text', models.TextField(blank=True, help_text='Notification text', null=True)),
                ('data', models.JSONField(blank=True, help_text='Json dictionary', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('script', models.TextField(blank=True, help_text='Write the context generator script here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChatContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventhistory')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.templatecontext'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
