# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 08:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('S', 'Via SMS'), ('E', 'Via email'), ('P', 'Push notification'), ('HG', 'HTTP GET request'), ('HP', 'HTTP POST request')], max_length=2)),
                ('mobiles', models.TextField(blank=True, help_text='Comma seprated list of mobile numbers.', null=True)),
                ('emails', models.TextField(blank=True, help_text='Comma seprated list of emails.', null=True)),
                ('urls', models.TextField(blank=True, help_text='Comma seprated list of URLs.', null=True)),
                ('title', models.CharField(blank=True, help_text='Notification title', max_length=255, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, help_text='Notification text', null=True)),
                ('json', models.TextField(blank=True, help_text='Json dictionary', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('script', models.TextField(blank=True, help_text='Write the context generator script here.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.TemplateContext'),
        )
    ]
