# Generated by Django 2.2.16 on 2022-04-11 17:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='method',
            field=models.CharField(choices=[('S', 'Via SMS'), ('E', 'Via email'), ('P', 'Push notification'), ('HG', 'HTTP GET request'), ('HP', 'HTTP POST request'), ('TB', 'Telegram bot')], max_length=2),
        ),
        migrations.CreateModel(
            name='UserChatContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
