# Generated by Django 2.2.16 on 2022-04-11 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20220411_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatcontext',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 58, 41, 302629, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchatcontext',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
