# Generated by Django 2.2.16 on 2022-04-13 13:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20220411_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='json',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Json dictionary', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
