# Generated by Django 2.2.16 on 2022-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20220413_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emails',
            field=models.TextField(blank=True, help_text='Comma separated list of emails.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mobiles',
            field=models.TextField(blank=True, help_text='Comma separated list of mobile numbers.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='urls',
            field=models.TextField(blank=True, help_text='Comma separated list of URLs.', null=True),
        ),
    ]
