# Generated by Django 4.0.9 on 2026-04-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Chart', 'Chart'), ('Map', 'Map'), ('Table', 'Table'), ('Favorite', 'Favorite'), ('Other', 'Other')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Widgets',
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_type', models.CharField(choices=[('Dashboard', 'Dashboard'), ('List', 'List'), ('Details', 'Details'), ('Profile', 'Profile'), ('Favorite', 'Favorite'), ('Other', 'Other')], max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.userdevicetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Views',
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.userdevicetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.view')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.widget')),
            ],
            options={
                'verbose_name_plural': 'User Widgets',
            },
        ),
    ]
