# Generated by Django 2.2.16 on 2022-04-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDevice',
        ),
    ]
